services:
  app1:
    build:
      context: ./app1
    container_name: app1
    ports:
      - "5001:5001"
    networks:
      - pythonproject4_app-network
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Labi6123
      - DB_NAME=token_api
    volumes:
      - ./app1:/app

  app2:
    build:
      context: ./app2
    container_name: app2
    ports:
      - "5004:5004"
    networks:
      - pythonproject4_app-network
    volumes:
      - ./app2:/app

  mysql:
    image: mysql/mysql-server
    container_name: mysql
    networks:
      - pythonproject4_app-network
    environment:
      MYSQL_ROOT_PASSWORD: Labi6123
      MYSQL_DATABASE: token_api
    platform: linux/amd64
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  pythonproject4_app-network:

volumes:
  mysql-data:

